## 시리즈 연습 문제

#### 문제1.
: 필요한 패키지를 import하고, 별명을 만드시오.

#### 문제2.
: 다음의 조건에 따라 임의로 두 개의 시리즈 객체를 생성하시오.
-  조건1) 모두 문자열 인덱스를 가져야 하며,
-  조건2) 모두 시리즈에 공통적으로 포함되지 않는 인덱스가 있어야 한다.
-  조건3) 값과 시리즈 원소 개수도 임의 설정할 것

#### 문제3.
:다음의 시리즈 객체를 이용하여 사칙연산을 수행하고 결과를 출력하시오.

In [ ]:
# 시리즈 데이터
ex_s1 = pd.Series({'국어':95,'영어':80,'수학':75})
ex_s2 = pd.Series({'국어':95,'영어':80,'수학':75})

#### 문제4. 
: 문제3의 두 시리즈 객체를 이용하여 다음 연산을 수행한 결과를 쓰고 왜 그러한지 설명하시오.

In [ ]:
ex_s1 = pd.Series({'국어':95,'영어':80,'수학':75})
ex_s2 = pd.Series({'국어':95,'과학':80,'논술':75})

In [ ]:
ex_s1 - ex_s2

In [ ]:
ex_s1.values - ex_s2.values

#### 문제5. 
: 다음의 데이터를 이용하여 주어진 조건에 따라 시리즈 객체를  생성하시오.

In [ ]:
#  서울 : 9904312, 부산 : 3448737, 인천 : 2890451  대구 : 2466052    
#  1) 리스트를 이용하여 시리즈 생성
#  2) 딕셔너리를 이용하여 시리즈 생성

#### 문제6. 
: 문제5에서 생성한 시리즈에 대한 인덱스를 출력하시오.

#### 문제7. 
:문제5에서 생성한 시리즈에 대하여 세번째 인덱스의 값을 문자인덱스로 접근 후 출력하시오.

#### 문제8. 
: 문제5에서 생성한 시리즈에 대하여 문자인덱싱을 이용하여 부산, 인천, 대구의 값을 추출하시오.

#### 문제9. 
:다음 데이터를 이용하여 시리즈를 생성하고 데이터 순서는 서울, 부산, 인천, 대전 으로 설정하시오.( 딕셔너리 활용 )

In [ ]:
#   서울 9631482
#   부산 3393191
#   인천 2632035
#   대전 1490158

#### 문제 10
: 위에서 생성한 시리즈에 인구 라는 이름을 설정하시오

#### 문제 11
: 위에서 생성한 시리즈의 인구수가 3000000 이상인 도시를 출력하시오

#### 문제 12
: 위에서 생성한 시리즈의 서울 데이터를 11000000 으로 변경하세요

#### 문제 11
: 대전 데이터를 삭제하세요

#### 문제 12 
: 대구 데이터가 있는지 확인 하세요